ServiExpress/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('accounts/', include('django.contrib.auth.urls'))
]

core/urls.py
from django import urls
from django.urls import path
from .views import home, agendar, agregar_servicio, listar_servicio, editar_servicio, eliminar_servicio, registro, listar_hora, listar_usuario

urlpatterns = [
    path('', home, name="home"),
    path('agendar/', agendar, name="agendar"),
    path('agregar_servicio/', agregar_servicio, name="agregar_servicio"),
    path('listar_servicio/', listar_servicio, name="listar_servicio"),
    path('editar_servicio/<id>/', editar_servicio, name="editar_servicio"),
    path('eliminar_servicio/<id>/', eliminar_servicio, name="eliminar_servicio"),
    path('registro/', registro, name="registro"),
    path('listar_hora/', listar_hora, name="listar_hora"),
    path('listar_usuario', listar_usuario, name="listar_usuario")
]

core/models.py
from django.db import models
from django.db.models.fields.related import ForeignKey

# Create your models here.

class Fecha(models.Model):
    dia = models.CharField(max_length=30)

    def __str__(self):
        return self.dia

class Servicio(models.Model):
    nombre = models.CharField(max_length=30)
    tipo = models.CharField(max_length=30, null=True)
    precio = models.IntegerField(null=True)

    def __str__(self):
        return self.nombre

opc_hora = [
    [0, "8:00hrs. - 8:59hrs."],
    [1, "9:00hrs. - 9:59hrs."],
    [2, "10:00hrs. - 10:59hrs."],
    [3, "11:00hrs. - 11:59hrs."],
    [4, "12:00hrs. - 12:59hrs."],
    [5, "13:00hrs. - 13:59hrs."],
    [6, "14:00hrs. - 14:59hrs."]
]

class Agendar(models.Model):
    fecha = ForeignKey(Fecha, on_delete=models.PROTECT)
    servicio = ForeignKey(Servicio, on_delete=models.PROTECT)
    hora = models.IntegerField(choices=opc_hora)

    def __str__(self):
        return self.fecha.dia

class Usuario(models.Model):
    usuario = models.CharField(max_length=30)
    email = models.CharField(max_length=30)
    password = models.CharField(max_length=20)

    def __str__(self):
        return self.usuario

core/forms.py
from django import forms
from .models import Agendar, Servicio 
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class AgendarForm(forms.ModelForm):

    class Meta:
        model = Agendar
        fields = ["fecha", "servicio", "hora"]

class ServicioForm(forms.ModelForm):

    class Meta:
        model =  Servicio
        fields = ["nombre", "tipo", "precio"]

class CustomUserCreationForm(UserCreationForm):
    
    class Meta:
        model = User
        fields = ["username", "first_name", "last_name", "email", "password1", "password2"]

core/views.py
from django.shortcuts import render, redirect, get_object_or_404

from core.models import Agendar, Servicio
from .forms import AgendarForm, ServicioForm, CustomUserCreationForm
from django.contrib.auth import authenticate, login
from django.contrib.auth.models import User

# Create your views here.

def home(request):
    return render(request, 'core/home.html')


def agendar(request):
    data = {    
        'form' : AgendarForm()
    }
    
    if request.method == 'POST':
        formulario = AgendarForm(data=request.POST)
        if formulario.is_valid:
            formulario.save()
            data["alerta"] = "Hora Agendada"
        else:
            data['form'] = formulario

    return render(request, 'core/agendar.html', data)

def agregar_servicio(request):
    data = {
        'form' : ServicioForm()
    }

    if request.method == 'POST':
        formulario = ServicioForm(data=request.POST)
        if formulario.is_valid:
            formulario.save()
            data["alerta"] = "Servicio agregado"
        else:
            data['form'] = formulario


    return render(request, 'core/servicios/agregar.html', data)

def listar_servicio(request):
    servicios = Servicio.objects.all()

    data = {
        'servicios': servicios
    }

    return render(request, 'core/servicios/listar.html', data)

def editar_servicio(request, id):

    servicio = get_object_or_404(Servicio, id=id)

    data = {
        'form': ServicioForm(instance=servicio)
    }

    if request.method == 'POST':
        formulario = ServicioForm(data=request.POST, instance=servicio)
        if formulario.is_valid():
            formulario.save()
            return redirect(to='listar_servicio')
        data["form"] = formulario

    return render(request, 'core/servicios/editar.html', data)

def eliminar_servicio(request, id):
    servicio = get_object_or_404(Servicio, id=id)
    servicio.delete()
    return redirect(to='listar_servicio')

def registro(request):
    data = {
        'form' : CustomUserCreationForm
    }

    if request.method == 'POST':
        formulario = CustomUserCreationForm(data=request.POST)
        if formulario.is_valid():
            formulario.save()
            user = authenticate(username=formulario.cleaned_data["username"], password=formulario.cleaned_data["password1"])
            login(request, user)
            return redirect(to="home")
        data["form"] = formulario

    return render(request, 'registration/signup.html', data)

def listar_hora(request):
    horas = Agendar.objects.all()

    data = {
        'horas': horas
    }

    return render(request, 'core/horas/listar.html', data)

def listar_usuario(request):
    usuarios = User.objects.all()

    data = {
        'usuarios': usuarios
    }

    return render(request, 'core/usuarios/listar.html', data)

core/templates/core/agendar.html
{% load static %}
{% load crispy_forms_tags %}

<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/9bc017105e.js" crossorigin="anonymous"></script>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Great+Vibes&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Oswald:wght@200;300;400;500;600;700&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Oswald&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>Serviexpress | Agendar</title>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg dark-nav">
            <div class="container">               
                <a href="#" class="navbar-brand op-logo">ServiExpress</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="Menú de navegación">
                    <span class="navbar-toggler-icon"><i class="fas fa-bars op-vanbar-toggler-icon"></i></span>
                </button>
                <div class="collapse navbar-collapse op-navbar dark-nav" id="navbar">
                    <ul class="navbar-nav me-auto mb-2 mb-md-0 op-ul">
                        <li class="nav-item">
                            <a href="{% url 'home' %}" class="nav-link ml-lg-2 active">Inicio</a>
                        </li>
                        <li class="nav-item">
                            <a href="#" class="nav-link">Nosotros</a>
                        </li>
                        <li class="nav-item">
                            <a href="#" class="nav-link">Contacto</a>
                        </li>
                        {% if user.is_authenticated %}
                            <li class="nav-item">
                                <a href="{% url 'agendar' %}" class="nav-link">Agendar</a>
                            </li>
                            <li class="nav-item">
                                <a href="#" class="nav-link">{{user.username}}</a>
                            </li>
                            <li class="nav-item">
                                <a href="{% url 'logout' %}" class="nav-link"><i class="fas fa-door-closed"></i></a>
                            </li>
                        {% else %}
                        <li class="nav-item">
                            <a href="{% url 'login' %}" class="nav-link"><i class="fa fa-user-circle-o"></i></a>
                        </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <main class="container main-hour">
        <div class="row d-flex justify-content-center row-calendar">
            <h2 class="h2-hora">Agendar hora</h2>
            <div class="col-6">
                <form action="" method="POST">
                    {% csrf_token %}

                    {{ form | crispy }}
                    <div class="d-flex justify-content-end">
                        <button type="submit" class="mt-3 submit-hora">Agendar</button>
                    </div>
                </form>
                {{alerta}}
            </div>
        </div>
    </main>
<footer>
    <h2 class="op-footer-logo">ServiExpress</h2>
</footer>

    <!--Bootstraps-->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js" integrity="sha384-SR1sx49pcuLnqZUnnPwx6FCym0wLsk5JZuNx2bPPENzswTNFaQU1RDvt3wT4gWFG" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.min.js" integrity="sha384-j0CNLUeiqtyaRmlzUHCPZ+Gy5fQu0dQ6eZ/xAww941Ai1SxSY+0EQqNXNE6DZiVc" crossorigin="anonymous"></script>
    <!--Validación-->
    <script src="app.js"></script>

</body>
</html>

core/templates/core/home.html
{% load static %}

<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/9bc017105e.js" crossorigin="anonymous"></script>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Great+Vibes&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Oswald:wght@200;300;400;500;600;700&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Oswald&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>Serviexpress | Inicio</title>
</head>
<body>
    <header>
        <aside class="foto">
            <nav class="navbar navbar-expand-lg">
                <div class="container">               
                    <a href="#" class="navbar-brand op-logo">ServiExpress</a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="Menú de navegación">
                        <span class="navbar-toggler-icon"><i class="fas fa-bars op-vanbar-toggler-icon"></i></span>
                    </button>
                    <div class="collapse navbar-collapse op-navbar" id="navbar">
                        <ul class="navbar-nav me-auto mb-2 mb-md-0 op-ul">
                            <li class="nav-item">
                                <a href="#" class="nav-link ml-lg-2 active">Inicio</a>
                            </li>
                            <li class="nav-item">
                                <a href="#nosotros" class="nav-link">Nosotros</a>
                            </li>
                            <li class="nav-item">
                                <a href="#contacto" class="nav-link">Contacto</a>
                            </li>
                            {% if user.is_authenticated %}
                            <li class="nav-item">
                                <a href="{% url 'agendar' %}" class="nav-link">Agendar</a>
                            </li>
                            <li class="nav-item">
                                <a href="#" class="nav-link">{{user.username}}</a>
                            </li>
                            <li class="nav-item">
                                <a href="{% url 'logout' %}" class="nav-link"><i class="fas fa-door-closed"></i></a>
                            </li>
                            {% else %}
                            <li class="nav-item">
                                <a href="{% url 'login' %}" class="nav-link"><i class="fa fa-user-circle-o"></i></a>
                            </li>
                            {% endif %}
                            
                            {% if perms.core.add_servicio %}
                            <li class="nav-item">
                                <a href="{% url 'agregar_servicio' %}" class="nav-link"><i class="fas fa-plus-square"></i></i> Agregar</a>
                            </li>
                            {% endif %}
                            {% if perms.core.add_servicio %}
                            <li class="nav-item">
                                <a href="{% url 'listar_servicio' %}" class="nav-link"><i class="far fa-list-alt"></i> Servicios</a>
                            </li>
                            <li class="nav-item">
                                <a href="{% url 'listar_usuario' %}" class="nav-link"><i class="far fa-list-alt"></i> Usuarios</a>
                            </li>
                            <li class="nav-item">
                                <a href="{% url 'listar_hora' %}" class="nav-link"><i class="far fa-list-alt"></i> Horas</a>
                            </li>
                            {% endif %}
        
                        </ul>
                    </div>
                </div>
            </nav>
            <div class="op-titulo container">
                <div class="row op-titulo-row d-flex align-items-center justify-content-center">
                    <div class="op-titulo-texto col-5">
                        <h1 class="op-foto-titulo">TÚ TRANQUILO, <br> DÉJALO EN <br> NUESTRAS MANOS</h1>
                    </div>
                    <div class="op-titulo-boton col-5 d-flex align-items-center justify-content-center">
                        <button class="op-btn-agregar">Agendar hora <i class="far fa-calendar"></i></button>
                    </div>
                </div>
            </div>
        </aside>
    </header>
    <div class="container">
        <div class="row">
            <div class="col-12" id="nosotros">
                <h2 class="nosotros">NOSOTROS</h2>
                <p class="texto2"> Lorem ipsum dolor sit amet consectetur, adipisicing elit. Atque iste et placeat assumenda dolorem amet tempora debitis tenetur ea ducimus ut voluptatum modi similique cupiditate dolorum consectetur fuga repudiandae, impedit voluptatibus exercitationem eos quidem ad. Minus facere tempora perspiciatis repudiandae ullam ad ipsam velit? Quia, enim labore? Tempore minus, quibusdam non officiis necessitatibus dolore quae velit deserunt magnam, ad sed, voluptate reprehenderit iusto? Expedita sed alias est repudiandae laudantium vitae sunt, architecto vero voluptas. Inventore iure nobis facilis, tenetur aliquam debitis quibusdam ipsam aspernatur, iste quos, doloribus aut aperiam ad laboriosam repudiandae nam magni fugit sequi perferendis porro culpa qui?
                </p>
                <p class="texto2">Lorem ipsum dolor sit amet consectetur adipisicing elit. Suscipit ex perspiciatis maxime odit eligendi atque ab cum perferendis dolore voluptatem labore natus vel quis provident, culpa modi maiores, est sunt laboriosam rem corporis eum necessitatibus? Tenetur totam, a laudantium repellat adipisci quidem sed obcaecati quia odit commodi velit asperiores, aliquid eveniet non, minima omnis. Voluptates assumenda incidunt a fugiat nam officiis. Exercitationem nam eveniet provident vitae velit aperiam eligendi ipsam vero placeat ex dolore cum voluptatibus culpa veniam in repellendus totam eaque consequuntur, similique vel, et ipsum! Totam, autem ab repellat sunt incidunt error? Reprehenderit sit nesciunt exercitationem dignissimos nam soluta iste neque officiis. Laboriosam cupiditate animi eligendi fugit? Deserunt reprehenderit eum dolorum tempore, pariatur expedita illum excepturi rerum placeat? Beatae similique ad voluptates laborum necessitatibus, vitae quia quae illum, magnam voluptas animi hic minus nostrum voluptatum harum. Quam reiciendis totam inventore error odio molestias rerum voluptate ea, commodi aperiam!    
                </p>
                <p class="texto2">  Lorem, ipsum dolor sit amet consectetur adipisicing elit. Nostrum dolorum nihil ea totam voluptatem incidunt excepturi ex, delectus repellat impedit molestias libero? Ducimus, libero. Repellendus iusto omnis asperiores amet eveniet voluptatem quidem atque maiores, eum, dolorem, ducimus est. Ipsa aliquam doloribus voluptas praesentium veniam libero, nemo distinctio rem placeat nobis incidunt, tenetur unde aperiam. Neque doloribus distinctio dolore nesciunt quam! Id nam voluptatum repellat, nobis reiciendis quo repudiandae delectus numquam?</p>
                <p class="texto2">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Doloremque dolorem temporibus iure assumenda eligendi aut fugiat debitis itaque deleniti ex pariatur recusandae dolore enim rerum porro molestias libero inventore eum dolor, numquam quaerat vel. Aspernatur mollitia magni, vitae exercitationem nulla iusto labore expedita molestias, aperiam esse harum voluptas eligendi consequatur nesciunt cum eos quibusdam obcaecati voluptates culpa tempore. Facilis, quibusdam!
                </p>   
            </div>
        </div>
        <div class="row justify-content-end mt-3 align-items-center">
            <div class="col-5">
                <img class="imagen" src="{% static 'img/2.jpg' %}">
            </div>
            <div class="col-6">
                <h2 class="h21">PROFESIONALES</h2>
                <div class="barrita"></div>
                <p class="texto1">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Beatae, quis totam veritatis aspernatur enim nobis, at aut nulla eaque voluptates magni ducimus! Quaerat neque esse minus, cupiditate veniam officiis sit ipsum voluptatem laudantium. Quia doloremque rem libero illum modi cum explicabo iste qui odit! Ratione eum modi ipsum suscipit totam!</p>
                <p class="texto1">Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime, officia. Qui ipsam perferendis animi nulla repudiandae ducimus et recusandae voluptatum molestias, commodi molestiae expedita laboriosam dolorum hic eum, voluptatibus placeat atque aperiam cum, ad quasi? Possimus exercitationem iste ullam provident fugiat aliquid doloribus omnis at laudantium impedit. Non porro quae voluptas. Distinctio itaque asperiores quod nihil velit, omnis quaerat est?</p>
            </div>
        </div>
        <div class="row justify-content-start mt-3 align-items-center">
            <div class="col-6">
                <h2 class="h22">RESPONSABLES</h2>
                <div class="barrita"></div>
                <p class="texto1">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Beatae, quis totam veritatis aspernatur enim nobis, at aut nulla eaque voluptates magni ducimus! Quaerat neque esse minus, cupiditate veniam officiis sit ipsum voluptatem laudantium. Quia doloremque rem libero illum modi cum explicabo iste qui odit! Ratione eum modi ipsum suscipit totam!</p>
                <p class="texto1">Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime, officia. Qui ipsam perferendis animi nulla repudiandae ducimus et recusandae voluptatum molestias, commodi molestiae expedita laboriosam dolorum hic eum, voluptatibus placeat atque aperiam cum, ad quasi? Possimus exercitationem iste ullam provident fugiat aliquid doloribus omnis at laudantium impedit. Non porro quae voluptas. Distinctio itaque asperiores quod nihil velit, omnis quaerat est?</p>
            </div>
            <div class="col-5">
                <img class="imagen" src="{% static 'img/1.jpg' %}">
            </div>
        </div>
    </div>
    <div class="container-contacto" id="contacto">
        <form>
            <h2 class="h2c">CONTACTO</h2>
            <label class="label-cont">Nombre</label>
            <input class="input1" type="text" name="nombre" >
            <label class="label-cont">Correo</label>
            <input class="input1" type="text" name="correo">
            <label class="label-cont">Mensaje</label>
            <textarea name="mensaje"></textarea>
            <td>
            <input class="boton" type="reset" value="Limpiar">
            <input class="boton" type="button" value="Enviar" id="boton">
            </td>
        </form>
    </div>
<footer>
    <h2 class="op-footer-logo">ServiExpress</h2>
</footer>

    <!--Bootstraps-->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js" integrity="sha384-SR1sx49pcuLnqZUnnPwx6FCym0wLsk5JZuNx2bPPENzswTNFaQU1RDvt3wT4gWFG" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.min.js" integrity="sha384-j0CNLUeiqtyaRmlzUHCPZ+Gy5fQu0dQ6eZ/xAww941Ai1SxSY+0EQqNXNE6DZiVc" crossorigin="anonymous"></script>
    <!--Validación-->
    <script src="app.js"></script>

</body>
</html>

core/templates/core/servicios/listar.html
{% load static %}
{% load crispy_forms_tags %}

<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/9bc017105e.js" crossorigin="anonymous"></script>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Great+Vibes&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Oswald:wght@200;300;400;500;600;700&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Oswald&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>Serviexpress | Listar Servicio</title>
</head>
<body class="crud-body">
    <header>
        <nav class="navbar navbar-expand-lg dark-nav">
            <div class="container">               
                <a href="#" class="navbar-brand op-logo">ServiExpress</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="Menú de navegación">
                    <span class="navbar-toggler-icon"><i class="fas fa-bars op-vanbar-toggler-icon"></i></span>
                </button>
                <div class="collapse navbar-collapse op-navbar dark-nav" id="navbar">
                    <ul class="navbar-nav me-auto mb-2 mb-md-0 op-ul">
                        <li class="nav-item">
                            <a href="{% url 'home' %}" class="nav-link ml-lg-2 active">Inicio</a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'agregar_servicio' %}" class="nav-link"><i class="fas fa-plus-square"></i></i> Agregar</a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'listar_servicio' %}" class="nav-link"><i class="far fa-list-alt"></i> Listar</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container crud-cont">
        <div class="row d-flex justify-content-center">
            <div class="col-6 crud-form my-4">
                <h1 class="text-center">Servicios</h1>
                <table class="table table-striped table-hover">
                    <tr>
                        <th>Servicio</th>
                        <th>Tipo</th>
                        <th>Precio</th>
                        <th>Administrar</th>
                    </tr>

                    {% for s in servicios %}
                    <tr>
                        <td>{{s.nombre}}</td>
                        <td>{{s.tipo}}</td>
                        <td>{{s.precio}}</td>
                        <td>
                            {% if perms.core.change_servicio %}
                            <a href="{% url 'editar_servicio' s.id %}" class="btn btn-info"><i class="fas fa-edit"></i></a>
                            {% endif %}
                            {% if perms.core.delete_servicio %}
                            <a href="{% url 'eliminar_servicio' s.id %}" class="btn btn-danger"><i class="fas fa-trash-alt"></i></a>
                            {% endif %}
                        </td>
                    </tr>
                    {% endfor %}
                </table>
            </div>
        </div>
    </div>
<footer>
    <h2 class="op-footer-logo">ServiExpress</h2>
</footer>

    <!--Bootstraps-->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js" integrity="sha384-SR1sx49pcuLnqZUnnPwx6FCym0wLsk5JZuNx2bPPENzswTNFaQU1RDvt3wT4gWFG" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.min.js" integrity="sha384-j0CNLUeiqtyaRmlzUHCPZ+Gy5fQu0dQ6eZ/xAww941Ai1SxSY+0EQqNXNE6DZiVc" crossorigin="anonymous"></script>
    <!--Validación-->
    <script src="app.js"></script>

</body>
</html>